# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/loading_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loadingScreen(object):
    def setupUi(self, loadingScreen):
        loadingScreen.setObjectName("loadingScreen")
        loadingScreen.resize(829, 469)
        loadingScreen.setStyleSheet("QWidget {\n"
"    background: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0,\n"
"        x2:1, y2:1,\n"
"        stop:0 #f8bbd0,   /* Light Rose Pink */\n"
"        stop:0.3 #b3e5fc, /* Light Sky Blue */\n"
"        stop:0.6 #fff9c4, /* Pale Yellow */\n"
"        stop:1 #b2ebf2    /* Soft Aqua Mint */\n"
"    );\n"
"}\n"
"\n"
"QLabel#welcomeLabel {\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: #3f51b5;  /* Medium Indigo - lighter than before */\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"QLabel#loadingLabel {\n"
"    font-size: 17px;\n"
"    color: #455a64; /* Softer graphite-gray tone */\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"QLabel#chatbotIcon {\n"
"    qproperty-alignment: AlignHCenter | AlignVCenter;\n"
"}\n"
"")
        self.WelcomeLabel = QtWidgets.QLabel(loadingScreen)
        self.WelcomeLabel.setGeometry(QtCore.QRect(110, 150, 641, 91))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.WelcomeLabel.setFont(font)
        self.WelcomeLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.25); /* More translucent */\n"
"    color: #1a237e;  /* Deep Indigo for calm contrast */\n"
"    font-family: \'Poppins\';\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"    border-radius: 16px;\n"
"    padding: 12px 20px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.3); /* subtle glass edge */\n"
"    backdrop-filter: blur(10px); /* glassmorphism blur */\n"
"    -webkit-backdrop-filter: blur(10px); /* Safari support */\n"
"    box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1); /* subtle depth */\n"
"}\n"
"")
        self.WelcomeLabel.setObjectName("WelcomeLabel")
        self.chatbotanimation = QtWidgets.QLabel(loadingScreen)
        self.chatbotanimation.setGeometry(QtCore.QRect(230, 240, 141, 121))
        self.chatbotanimation.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.25); /* More translucent */\n"
"    color: #1a237e;  /* Deep Indigo for calm contrast */\n"
"    font-family: \'Poppins\';\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"    border-radius: 16px;\n"
"    padding: 12px 20px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.3); /* subtle glass edge */\n"
"    backdrop-filter: blur(10px); /* glassmorphism blur */\n"
"    -webkit-backdrop-filter: blur(10px); /* Safari support */\n"
"    box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1); /* subtle depth */\n"
"}\n"
"")
        self.chatbotanimation.setText("")
        self.chatbotanimation.setPixmap(QtGui.QPixmap("C:/Users/ramla/Downloads/Animation - 1746873587109.gif"))
        self.chatbotanimation.setAlignment(QtCore.Qt.AlignCenter)
        self.chatbotanimation.setObjectName("chatbotanimation")
        self.namelabel = QtWidgets.QLabel(loadingScreen)
        self.namelabel.setGeometry(QtCore.QRect(350, 240, 291, 91))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.namelabel.setFont(font)
        self.namelabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.25); /* More translucent */\n"
"    color: #1a237e;  /* Deep Indigo for calm contrast */\n"
"    font-family: \'Poppins\';\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"    border-radius: 16px;\n"
"    padding: 12px 20px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.3); /* subtle glass edge */\n"
"    backdrop-filter: blur(10px); /* glassmorphism blur */\n"
"    -webkit-backdrop-filter: blur(10px); /* Safari support */\n"
"    box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1); /* subtle depth */\n"
"}\n"
"")
        self.namelabel.setObjectName("namelabel")
        self.loadinganimation = QtWidgets.QLabel(loadingScreen)
        self.loadinganimation.setGeometry(QtCore.QRect(240, 320, 401, 41))
        self.loadinganimation.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.25); /* More translucent */\n"
"    color: #1a237e;  /* Deep Indigo for calm contrast */\n"
"    font-family: \'Poppins\';\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"    border-radius: 16px;\n"
"    padding: 12px 20px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.3); /* subtle glass edge */\n"
"    backdrop-filter: blur(10px); /* glassmorphism blur */\n"
"    -webkit-backdrop-filter: blur(10px); /* Safari support */\n"
"    box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1); /* subtle depth */\n"
"}\n"
"")
        self.loadinganimation.setText("")
        self.loadinganimation.setPixmap(QtGui.QPixmap("C:/Users/ramla/Downloads/Animation - 1746874294705.gif"))
        self.loadinganimation.setAlignment(QtCore.Qt.AlignCenter)
        self.loadinganimation.setObjectName("loadinganimation")
        self.particleview = QtWidgets.QGraphicsView(loadingScreen)
        self.particleview.setGeometry(QtCore.QRect(-25, -19, 871, 491))
        self.particleview.setObjectName("particleview")
        self.particleview.raise_()
        self.WelcomeLabel.raise_()
        self.chatbotanimation.raise_()
        self.namelabel.raise_()
        self.loadinganimation.raise_()

        self.retranslateUi(loadingScreen)
        QtCore.QMetaObject.connectSlotsByName(loadingScreen)

    def retranslateUi(self, loadingScreen):
        _translate = QtCore.QCoreApplication.translate
        loadingScreen.setWindowTitle(_translate("loadingScreen", "MindMate"))
        self.WelcomeLabel.setText(_translate("loadingScreen", "Welcome to Your Mental Health Chatbot"))
        self.namelabel.setText(_translate("loadingScreen", "Your Mind Mate"))
