# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/loasing_screen_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(797, 565)
        Form.setStyleSheet("QWidget {\n"
"    background: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0,\n"
"        x2:1, y2:1,\n"
"        stop:0 #f8bbd0,\n"
"        stop:0.3 #b3e5fc,\n"
"        stop:0.6 #fff9c4,\n"
"        stop:1 #b2ebf2\n"
"    );\n"
"}\n"
"")
        self.glassCard = QtWidgets.QFrame(Form)
        self.glassCard.setGeometry(QtCore.QRect(220, 80, 361, 411))
        self.glassCard.setStyleSheet("QFrame#glassCard {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"    border-radius: 30px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.3);\n"
"    backdrop-filter: blur(12px); /* for visual reference only */\n"
"    -webkit-backdrop-filter: blur(12px);\n"
"    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.15);\n"
"}\n"
"")
        self.glassCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.glassCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.glassCard.setObjectName("glassCard")
        self.botIcon = QtWidgets.QLabel(self.glassCard)
        self.botIcon.setGeometry(QtCore.QRect(80, 70, 211, 171))
        self.botIcon.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.botIcon.setText("")
        self.botIcon.setPixmap(QtGui.QPixmap("C:/Users/ramla/Downloads/Animation - 1746873587109.gif"))
        self.botIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.botIcon.setObjectName("botIcon")
        self.titleLabel = QtWidgets.QLabel(self.glassCard)
        self.titleLabel.setGeometry(QtCore.QRect(70, 240, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(28)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.titleLabel.setObjectName("titleLabel")
        self.subtitleLabel = QtWidgets.QLabel(self.glassCard)
        self.subtitleLabel.setGeometry(QtCore.QRect(10, 290, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.subtitleLabel.setFont(font)
        self.subtitleLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.animationLabel = QtWidgets.QLabel(self.glassCard)
        self.animationLabel.setGeometry(QtCore.QRect(140, 320, 91, 81))
        self.animationLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.animationLabel.setText("")
        self.animationLabel.setPixmap(QtGui.QPixmap("C:/Users/ramla/Downloads/Animation - 1746882257108.gif"))
        self.animationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.animationLabel.setObjectName("animationLabel")
        self.welcomeLabel = QtWidgets.QLabel(self.glassCard)
        self.welcomeLabel.setGeometry(QtCore.QRect(80, 20, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.welcomeLabel.setObjectName("welcomeLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titleLabel.setText(_translate("Form", "MindMate"))
        self.subtitleLabel.setText(_translate("Form", "Your Mental Health Companion"))
        self.welcomeLabel.setText(_translate("Form", "Welcome to"))
