# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 550)
        MainWindow.setStyleSheet("/* 🌈 Soft pastel background for full window */\n"
"QMainWindow, QWidget {\n"
"    background: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #fce4ec,\n"
"        stop:0.3 #e3f2fd,\n"
"        stop:0.6 #fffde7,\n"
"        stop:1 #e0f7fa\n"
"    );\n"
"    font-family: \"Poppins\", \"Segoe UI\", sans-serif;\n"
"    color: #2e2e2e;\n"
"}\n"
"QLabel#headerLabel {\n"
"    font-size: 26px;\n"
"    font-weight: bold;\n"
"    color: #263238;\n"
"    qproperty-alignment: AlignCenter;\n"
"    background-color: transparent;\n"
"}\n"
"QLabel#historyLabel {\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    color: #37474f;\n"
"    padding: 8px;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollArea, QListWidget {\n"
"    background-color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #cfd8dc;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton#sendButton {\n"
"    background-color: #4dd0e1;\n"
"    color: #004d40;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton#sendButton:hover {\n"
"    background-color: #26c6da;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(817, 482))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setMaximumSize(QtCore.QSize(250, 500))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.historyLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(18)
        self.historyLabel.setFont(font)
        self.historyLabel.setObjectName("historyLabel")
        self.verticalLayout.addWidget(self.historyLabel)
        self.historyList = QtWidgets.QListWidget(self.widget)
        self.historyList.setObjectName("historyList")
        self.verticalLayout.addWidget(self.historyList)
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerLabel = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        self.headerLabel.setFont(font)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout_2.addWidget(self.headerLabel)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.historyLabel.setText(_translate("MainWindow", "History"))
        self.headerLabel.setText(_translate("MainWindow", "MindMate"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
